"""empty message

Revision ID: 4519b32cb1e5
Revises: c87718947f5c
Create Date: 2022-12-24 16:55:31.806349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4519b32cb1e5'
down_revision = 'c87718947f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('call_the_waiter_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('desk_private_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desk_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['desk_id'], ['desk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('table_private_key')
    op.drop_table('table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('call_the_waiter_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('table_private_key',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.INTEGER(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('private_key', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('desk_private_key')
    op.drop_table('desk')
    # ### end Alembic commands ###
