"""empty message

Revision ID: c87718947f5c
Revises: 2433f3e60ed6
Create Date: 2022-12-22 23:21:55.462406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87718947f5c'
down_revision = '2433f3e60ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('telegram_channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'telegram_channel')
    # ### end Alembic commands ###
